# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: addc48c8eca048af00c7fc773da9305fb052d6724322150c0d4207bbebb93a042d6ad3daebdfa473cb2aef08b3e4d932253cf909e582d1cb6ee96e48f1513725

test:
  secret_key_base: 7fca05a183513270f07c6e5c2dec6d331aab4113b3f7561510a42bf0f12ecda0e3eb87b6fef9b032527e0f4cda3612cc17d3fb2c286f39c68daaeb032db9b69a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
